openapi: "3.0.3"
info:
  title: Share Cart API
  version: "1.0"
servers:
  - url: http://localhost:8081
paths:
  /test:
    get:
      parameters:
        - $ref: "#/components/parameters/Authorization"
      responses:
        "200":
          $ref: "#/components/responses/DefaultSuccess"
        "500":
          $ref: "#/components/responses/500InternalServerError"

  /sign-up:
    post:
      parameters:
        - $ref: "#/components/parameters/Authorization"
      requestBody:
        $ref: "#/components/requestBodies/SignUp"
      responses:
        "201":
          $ref: "#/components/responses/DefaultSuccess"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500InternalServerError"

components:
  parameters:
    Authorization:
      in: header
      name: Authorization
      schema:
        type: string
      required: true
      description: Bearer token

  requestBodies:
    SignUp:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                example: "your_name"

  responses:
    DefaultSuccess:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Success"
            required:
              - message

    401UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Unauthorized"
            required:
              - message

    403ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Forbidden"
            required:
              - message

    500InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Internal Server Error"
            required:
              - message
