# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  path_filters:
    - "!api/app/oas/**"
    - "!api/app/infra/boiler/**"
    - "!api/docs/tbls/generated/**"
    - "!**/mock/**"
    - "!**/go.mod"
    - "!**/go.sum"
    - "!**/cspell.jsonc"
    - "!.coderabbit.yaml" # cspell:disable-line
    - "!infra/terraform/remote/.terraform.lock.hcl"
