services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./api/:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: share_cart
      POSTGRES_HOST: db:5432
    ports:
      - "8081:8081"
    command: ["air", "-c", ".air.toml"]
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./web/:/app/
      - share-cart-node-modules:/app/share-cart/node_modules
    ports:
      - "5173:5173"
    environment:
      API_HOST: http://api:8081
    env_file:
      - ./web/.env
    working_dir: /app/share-cart
    command: ["yarn", "dev"]
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: share_cart
    ports:
      - "5432:5432"
    volumes:
      - share-cart-db-data:/var/lib/postgresql/data

volumes:
  share-cart-node-modules:
  share-cart-db-data:
