services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./api/:/app/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8081:8081"
    env_file:
      - ./api/.env
    command: ["air", "-c", ".air.toml"]
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local
      # target: production
    volumes:
      - ./web/:/app/
    ports:
      - "5173:5173"
    environment:
      API_HOST: http://api:8081
      PORT: 5173
    env_file:
      - ./web/.env
    command: ["pnpm", "dev"]
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - share-cart-db-data:/var/lib/postgresql/data

volumes:
  share-cart-db-data:
