services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./api/:/app/
    ports:
      - "8081:8081"
    command: ["air", "-c", ".air.toml"]
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./web/:/app/
      - share-cart-node-modules:/app/share-cart/node_modules
    ports:
      - "5173:5173"
    environment:
      - API_HOST=http://api:8081
    working_dir: /app/share-cart
    command: ["yarn", "dev"]

volumes:
  share-cart-node-modules:
