// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// MarketMarketIdDeleteParams is parameters of DELETE /market/{marketId} operation.
type MarketMarketIdDeleteParams struct {
	// The market ID(uuid).
	MarketId string
}

func unpackMarketMarketIdDeleteParams(packed middleware.Parameters) (params MarketMarketIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "marketId",
			In:   "path",
		}
		params.MarketId = packed[key].(string)
	}
	return params
}

func decodeMarketMarketIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params MarketMarketIdDeleteParams, _ error) {
	// Decode path: marketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "marketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.MarketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "marketId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// MarketMarketIdGetParams is parameters of GET /market/{marketId} operation.
type MarketMarketIdGetParams struct {
	// The market ID(uuid).
	MarketId string
}

func unpackMarketMarketIdGetParams(packed middleware.Parameters) (params MarketMarketIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "marketId",
			In:   "path",
		}
		params.MarketId = packed[key].(string)
	}
	return params
}

func decodeMarketMarketIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params MarketMarketIdGetParams, _ error) {
	// Decode path: marketId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "marketId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.MarketId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "marketId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
