// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/go-faster/errors"
)

func (s MarketGetOKApplicationJSON) Validate() error {
	alias := ([]MarketGetOKItem)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
