// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// MarketGet implements GET /market operation.
//
// GET /market
func (UnimplementedHandler) MarketGet(ctx context.Context) (r MarketGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SignUpPost implements POST /sign-up operation.
//
// POST /sign-up
func (UnimplementedHandler) SignUpPost(ctx context.Context, req *SignUpPostReq) (r SignUpPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestGet implements GET /test operation.
//
// GET /test
func (UnimplementedHandler) TestGet(ctx context.Context) (r TestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
