// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// LoginPost implements POST /login operation.
//
// POST /login
func (UnimplementedHandler) LoginPost(ctx context.Context, req *LoginPostReq) (r LoginPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestGet implements GET /test operation.
//
// GET /test
func (UnimplementedHandler) TestGet(ctx context.Context) (r TestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
