import createClient from "openapi-fetch";
import { config } from "./config";
import type { paths } from "./share-cart"; // generated by openapi-typescript

export function shareCartClient(accessToken: string | undefined) {
	const client = createClient<paths>({ baseUrl: config.API_HOST });
	client.use({
		async onRequest({ request }) {
			request.headers.set("Authorization", `Bearer ${accessToken ?? "empty"}`);
			return request;
		},
	});
	return client;
}
