# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: gen
generate:
  echo-server: true
  # client: true
  models: true
  embedded-spec: true
output: api.gen.go
output-options:
  skip-prune: true
