// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	AuthSubjects string
	Items        string
	Markets      string
	Users        string
}{
	AuthSubjects: "auth_subjects",
	Items:        "items",
	Markets:      "markets",
	Users:        "users",
}
