output = "app/infra/boiler"
pkgname = "boiler"
wipe = true
no-tests = true

[[types]]
[types.match]
name = "id"
[types.replace]
type = "uuid.UUID"
[types.imports]
third_party = ['"github.com/google/uuid"']

[psql]
dbname = "share_cart"
host = "db"
port = 5432
user = "postgres"
pass = "postgres"
sslmode = "disable"
schema = "public"
