version: "3"

tasks:
  generate:
    cmd: ogen --package oas --target app/oas --clean docs/openapi.yaml
    sources:
      - docs/openapi.yaml

  dev:
    cmds:
      - task: generate
      - task: graph

  graph:
    cmd: godepgraph -o .,api -s . | dot -Tpng -o ./docs/dependency.png
    sources:
      - ./**/*.go

  inspect:
    cmd: atlas schema inspect -u "postgres://postgres:postgres@db:5432/share_cart?sslmode=disable" > ./app/infra/db/schema.hcl
