version: "3"

tasks:
  generate:
    cmd: ogen --package oas --target app/oas --clean docs/openapi.yaml
    sources:
      - docs/openapi.yaml

  air:
    cmd: air -c .air.toml

  dev:
    cmds:
      - task: generate
      - task: air
