version: "3"

env:
  POSTGRES_URL:
    sh: echo postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable
  SCHEMA_FILES:
    sh: find docs/atlas -type f | sed 's|^|file://|' | paste -sd ","

tasks:
  dev:
    cmds:
      - task: generate
      - task: graph

  generate:
    cmd: ogen --package oas --target app/oas --clean --config docs/openapi/ogen_config.yaml docs/openapi/schema/root.yaml
    sources:
      - docs/openapi/schema/root.yaml

  graph:
    cmd: godepgraph -o .,api -p api/app/shared -s . | dot -Tpng -o ./docs/dependency.png # cspell:disable-line
    sources:
      - ./**/*.go

  plan:
    cmd: atlas schema apply -u $POSTGRES_URL --to $SCHEMA_FILES --dry-run

  apply:
    cmds:
      - atlas schema apply -u $POSTGRES_URL --to $SCHEMA_FILES
      - task: tbls
      - task: sqlboiler

  apply_ci:
    cmds:
      - atlas schema apply -u $POSTGRES_URL --to $SCHEMA_FILES --auto-approve

  sqlboiler:
    cmd: sqlboiler psql

  tbls:
    dir: docs
    cmd: tbls doc $POSTGRES_URL --rm-dist -c tbls/.tbls.yaml

  mockgen_base:
    vars:
      INTERFACE_FILES:
        sh: find {{.INTERFACE_DIR}} -maxdepth 1 -name "*.go" -type f | sed 's!^.*/!!' # cspell:disable-line
    cmds:
      - rm -rf {{.INTERFACE_DIR}}/mock
      - for: { var: INTERFACE_FILES }
        cmd: mockgen -source={{.INTERFACE_DIR}}/{{.ITEM}} -destination={{.INTERFACE_DIR}}/mock/{{.ITEM}}
    internal: true
    requires:
      vars: [INTERFACE_DIR]

  mockgen:
    cmds:
      - task: mockgen_base
        vars:
          INTERFACE_DIR: app/domain/repository/db
