version: "3"

env:
  POSTGRES_HOST: db:5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: share_cart

  DB_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable
  SCHEMA_FILE: file://./app/infra/db/schema.hcl

tasks:
  generate:
    cmd: ogen --package oas --target app/oas --clean docs/openapi.yaml
    sources:
      - docs/openapi.yaml

  dev:
    cmds:
      - task: generate
      - task: graph

  graph:
    cmd: godepgraph -o .,api -s . | dot -Tpng -o ./docs/dependency.png # cspell:disable-line
    sources:
      - ./**/*.go

  apply:
    cmd: atlas schema apply -u {{.PG_URL}} --to $SCHEMA_FILE
    vars:
      PG_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable

  plan:
    cmd: atlas schema apply -u {{.PG_URL}} --to $SCHEMA_FILE --dry-run
    vars:
      PG_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable
