on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/api-deploy.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{secrets.WIF_PROVIDER_NAME}}
          service_account: ${{secrets.WIF_SA_EMAIL}}
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "api"
          image: "asia-northeast1-docker.pkg.dev/coastal-fiber-430001-s0/api-repo/api:latest"

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
