on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "api/docs/atlas/**"
      - ".github/workflows/atlas-plan.yaml"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{secrets.WIF_PROVIDER_NAME}}
          service_account: ${{secrets.WIF_SA_EMAIL}}

      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Download and install Atlas CLI
        run: |
          curl -sSf https://atlasgo.sh | sh -s -- -y
      - name: set env
        run: |
          echo POSTGRES_USER="$(gcloud secrets versions access latest --secret='supabase_user')" >> $GITHUB_ENV
          echo POSTGRES_PASSWORD="$(gcloud secrets versions access latest --secret='supabase_password')" >> $GITHUB_ENV
          echo POSTGRES_DB="$(gcloud secrets versions access latest --secret='supabase_db_dev')" >> $GITHUB_ENV
          echo POSTGRES_HOST="$(gcloud secrets versions access latest --secret='supabase_host')" >> $GITHUB_ENV
          echo POSTGRES_PORT="$(gcloud secrets versions access latest --secret='supabase_port')" >> $GITHUB_ENV
      - id: plan
        run: task plan
