on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "api/docs/atlas/**"
      - ".github/workflows/atlas-plan.yaml"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{secrets.WIF_PROVIDER_NAME}}
          service_account: ${{secrets.WIF_SA_EMAIL}}
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: export variables
        run: |
          POSTGRES_PORT=$(gcloud secrets versions access latest --secret="supabase_port")
          export POSTGRES_PORT

# export POSTGRES_USER=$(gcloud secrets versions access latest --secret="supabase_user")
# export POSTGRES_PASSWORD=$(gcloud secrets versions access latest --secret="supabase_password")
# export POSTGRES_DB=$(gcloud secrets versions access latest --secret="supabase_db_dev")
# export POSTGRES_HOST=$(gcloud secrets versions access latest --secret="supabase_host")
# export POSTGRES_PORT=$(gcloud secrets versions access latest --secret="

# POSTGRES_USER="postgres"
# POSTGRES_PASSWORD="postgres"
# POSTGRES_DB="share_cart"
# POSTGRES_HOST="db"
# POSTGRES_PORT="5432"
