on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "infra/repository/**.tf"
      - ".github/workflows/bases/plan.yaml"
      - ".github/workflows/github-plan.yaml"

jobs:
  plan:
    uses: ./.github/workflows/_base_plan.yaml
    with:
      working-directory: infra/repository
