on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "infra/repository/**.tf"
      - ".github/workflows/bases/plan.yaml"
      - ".github/workflows/github-plan.yaml"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      # - id: auth
      #   uses: "google-github-actions/auth@v2"
      #   with:
      #     project_id: "kamono-personal"
      #     workload_identity_provider: ${{ secrets.WIF_POOL_PROVIDER_ID }}
      #     service_account: ${{ secrets.WIF_SA_EMAIL }}
      - uses: ./.github/workflows/actions/terraform-plan
        # with:
        #   working-directory: infra/repository
