on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "infra/repository/**.tf"

jobs:
  plan:
    uses: ./.github/workflows/bases/plan.yaml
    with:
      working-directory: infra/repository
