on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/terraform/remote/**"
      - ".github/workflows/terraform-apply.yaml"

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/remote
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{secrets.WIF_PROVIDER_NAME}}
          service_account: ${{secrets.WIF_SA_EMAIL}}
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
