version: "3"

interval: 50ms

includes:
  dep: taskfiles/dependency.yaml

tasks:
  generate:
    cmd: pnpm dlx openapi-typescript ../api/docs/openapi/schema/root.yaml -o share-cart/lib/share-cart.d.ts
    sources:
      - "../api/docs/openapi/schema/root.yaml"
    generates:
      - "share-cart/lib/share-cart.d.ts"

  gen_env:
    cmd: pnpm dlx gen-env-template .env .env.example
    sources:
      - ".env"
    generates:
      - ".env.example"
