version: "3"

interval: 50ms

tasks:
  dev:
    deps:
      - generate
      - gen_env
      - dep_graph

  generate:
    cmd: bunx -y openapi-typescript ../api/docs/openapi/schema/root.yaml -o share-cart-bun/app/models/schema.d.ts
    sources:
      - "../api/docs/openapi/schema/root.yaml"
    generates:
      - "share-cart-bun/app/models/schema.d.ts"

  format:
    dir: share-cart-bun/app
    cmds:
      - bunx biome format --write
    sources:
      - "**/*.tsx"
      - "**/*.ts"

  gen_env:
    cmd: bunx gen-env-template .env .env.example
    sources:
      - ".env"
    generates:
      - ".env.example"

  dep_graph:
    dir: share-cart-bun
    cmd: bunx depcruise app --include-only "^app" --output-type dot | dot -Tpng > dependency-graph.png # cspell: disable-line
    sources:
      - "app/**/*.ts"
      - "app/**/*.tsx"
    generates:
      - "dependency-graph.png"
