version: "3"

interval: 50ms

tasks:
  dev:
    cmds:
      - task: generate
      - task: format
      - task: gen_env
      - task: dep_graph

  generate:
    cmd: npx -y openapi-typescript ../api/docs/openapi.yaml -o share-cart/app/models/schema.d.ts
    sources:
      - "../api/docs/openapi.yaml"
    generates:
      - "share-cart/app/models/schema.d.ts"

  format:
    cmds:
      - biome format --write
    sources:
      - "**/*.tsx"
      - "**/*.ts"

  gen_env:
    cmd: npx gen-env-template .env .env.example
    sources:
      - ".env"
    generates:
      - ".env.example"

  dep_graph:
    dir: share-cart
    cmd: npx depcruise app --include-only "^app" --output-type dot | dot -Tpng > dependency-graph.png # cspell: disable-line
    sources:
      - "app/**/*.ts"
      - "app/**/*.tsx"
    generates:
      - "dependency-graph.png"
